syntax="proto3";

package server;

option go_package = "internal/server";

service KvStore {
    rpc SetHandler(SetRequest) returns (SetResponse);
    rpc GetHandler(GetRequest) returns (GetResponse);
    rpc DeleteHandler(DeleteRequest) returns (DeleteResponse); 
}

message SetRequest {
    string key = 1;
    string value = 2;
}

message GetRequest {
    string key = 1;
}

message  DeleteRequest {
    string key = 1;
}

message SetResponse {
    bool success = 1;
}

message GetResponse {
    bool found = 1;
    string value = 2;
}

message DeleteResponse {
    bool success = 1;
}